"""Canonical WAF fingerprints shared by passive and active detectors."""

import re
from typing import Any, Dict, List, Mapping


WAF_SIGNATURES: Dict[str, Dict[str, Any]] = {
    "Cloudflare": {
        "headers": {"server": r"cloudflare", "cf-ray": r".+"},
        "header_names": r"^cf-",
        "cookies": r"__cflb|__cfuid|cf_clearance|__cf_bm",
        "body": r"cloudflare|ray id|cf-error",
    },
    "AWS WAF": {
        "headers": {"x-amzn-requestid": r".+", "x-amz-cf-id": r".+"},
        "header_names": r"^x-amz|awselb",
        "body": r"aws|amazonaws",
    },
    "Akamai": {
        "headers": {"x-akamai-transformed": r".+", "server": r"akamai"},
        "header_names": r"akamai",
        "body": r"akamai|reference.*#\d+\.\w+",
    },
    "ModSecurity": {
        "headers": {"server": r"mod_security|modsecurity"},
        "body": r"mod_security|modsecurity|modsec|not acceptable|406 not acceptable",
    },
    "Sucuri": {
        "headers": {"server": r"sucuri", "x-sucuri-id": r".+"},
        "body": r"sucuri|cloudproxy",
    },
    "Imperva / Incapsula": {
        "headers": {"x-iinfo": r".+", "x-cdn": r"incapsula"},
        "cookies": r"incap_ses|visid_incap",
        "body": r"incapsula|imperva",
    },
    "F5 BIG-IP ASM": {
        "headers": {"server": r"big-?ip", "x-wa-info": r".+"},
        "header_names": r"bigip|x-cnection",
        "cookies": r"TS[a-z0-9]{6,}|BIGipServer",
        "body": r"the requested url was rejected|bigip|\bf5\b",
    },
    "Barracuda": {
        "headers": {"server": r"barracuda"},
        "cookies": r"barra_counter_session",
        "body": r"barracuda",
    },
    "Fortinet FortiWeb": {
        "headers": {"server": r"fortiweb"},
        "cookies": r"FORTIWAFSID",
        "body": r"fortigate|fortinet|fortiweb",
    },
    "Wordfence (WordPress)": {
        "body": r"wordfence|wfwaf-authcookie|generated by wordfence",
    },
    "DenyAll": {
        "headers": {"server": r"denyall"},
        "cookies": r"sessioncookie",
        "body": r"denyall",
    },
    "Citrix NetScaler": {
        "headers": {"via": r"ns-cache", "cneonction": r".+"},
        "cookies": r"ns_af|citrix_ns_id|NSC_",
        "body": r"ns transaction id|citrix|netscaler",
    },
    "Radware AppWall": {
        "headers": {"x-sl-compstate": r".+"},
        "body": r"radware|unauthorized activity",
    },
    "StackPath": {
        "headers": {"x-sp-url": r".+", "x-sp-waf": r".+"},
        "body": r"stackpath",
    },
    "Varnish": {
        "headers": {"via": r"varnish", "x-varnish": r".+"},
    },
}


WAF_METADATA: Dict[str, Dict[str, Any]] = {
    "Cloudflare": {"confidence": 1.0, "strategy": "encoding"},
    "AWS WAF": {"confidence": 0.85, "strategy": "encoding"},
    "Akamai": {"confidence": 0.9, "strategy": "tag_break"},
    "ModSecurity": {"confidence": 0.85, "strategy": "comment"},
    "Sucuri": {"confidence": 0.95, "strategy": "encoding"},
    "Imperva / Incapsula": {"confidence": 0.95, "strategy": "polyglot", "display_name": "Imperva"},
    "F5 BIG-IP ASM": {"confidence": 0.9, "strategy": "whitespace"},
    "Barracuda": {"confidence": 0.9, "strategy": "concatenation"},
    "Fortinet FortiWeb": {"confidence": 0.9, "strategy": "tag_break"},
    "DenyAll": {"confidence": 0.8, "strategy": "bypass_filter"},
    "Citrix NetScaler": {"confidence": 0.85, "strategy": "polyglot"},
}


def match_waf_signatures(response: Mapping[str, Any]) -> Dict[str, List[str]]:
    """Return WAF names and the normalized signals that matched them."""
    headers = {
        str(key).lower(): str(value).lower()
        for key, value in dict(response.get("headers") or {}).items()
    }
    cookies = str(response.get("cookies") or "")
    body = str(response.get("body") or "")
    hits: Dict[str, List[str]] = {}

    for waf_name, rules in WAF_SIGNATURES.items():
        sources: List[str] = []
        for header, pattern in rules.get("headers", {}).items():
            value = headers.get(header)
            if value and re.search(pattern, value, re.IGNORECASE):
                sources.append(f"header:{header}")

        header_name_pattern = rules.get("header_names")
        if header_name_pattern:
            for header in headers:
                if re.search(header_name_pattern, header, re.IGNORECASE):
                    sources.append(f"header:{header}")

        if rules.get("cookies") and cookies and re.search(rules["cookies"], cookies, re.IGNORECASE):
            sources.append("cookie")
        if rules.get("body") and body and re.search(rules["body"], body, re.IGNORECASE):
            sources.append("body")

        if sources:
            hits[waf_name] = list(dict.fromkeys(sources))

    return hits


__all__ = ["WAF_METADATA", "WAF_SIGNATURES", "match_waf_signatures"]
